import { Component } from '@angular/core';
import { CommonComponentsModule } from '../../../shared/modules/common-components.module';
import { CourseLetterComponent } from '../../../shared/components/course-letter/course-letter.component';
import { CardCourse } from '../../../shared/models/request/course-letter-request';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonComponentsModule, CourseLetterComponent, NgOptimizedImage],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {

  cardTempalte: CardCourse[] = [];

  constructor(){
    this.cardTempalte = [
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      },
      {
        logo: "https://blog.ayzweb.com/wp-content/uploads/homer.gif",
        career: "Medicina",
        courses: [
          "Matematica",
          "Fisica",
          "sexologia"
        ],
        students: [
          {
            name: "Gonzalo",
            secondName: "Erick",
            motherLastName: "Davila",
            fatherLastName: "Ñahui",
            nickname: "mongosaurio",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Jairo",
            secondName: "Anthony",
            motherLastName: "Caccya",
            fatherLastName: "Ñahui",
            nickname: "weberto",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Raul",
            secondName: "Jhonatan",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "pelao",
            edad: 21,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Renzo",
            secondName: "Fernando",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "menso",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
          {
            name: "Alejandro",
            secondName: "Ruben",
            motherLastName: "Velarde",
            fatherLastName: "Ñahui",
            nickname: "miPapi",
            edad: 20,
            codigo: "2013232231223",
            birthdate: new Date,
            photo: "",
            sex: "F",
            mail: "asd",
          },
        ]
      }
    ]
  }

}
